// Code generated by ndn tlv codegen DO NOT EDIT.
package merklelog

import (
	"encoding/binary"
	"io"

	"time"

	enc "github.com/named-data/ndnd/std/encoding"
)

type AppendRequestEncoder struct {
	Length uint

	DataHashes_subencoder []struct {
	}
}

type AppendRequestParsingContext struct {
}

func (encoder *AppendRequestEncoder) Init(value *AppendRequest) {
	{
		DataHashes_l := len(value.DataHashes)
		encoder.DataHashes_subencoder = make([]struct {
		}, DataHashes_l)
		for i := 0; i < DataHashes_l; i++ {
			pseudoEncoder := &encoder.DataHashes_subencoder[i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: value.DataHashes[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue

				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.DataHashes != nil {
		for seq_i, seq_v := range value.DataHashes {
			pseudoEncoder := &encoder.DataHashes_subencoder[seq_i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.DataHashes != nil {
					l += 3
					l += uint(enc.TLNum(len(value.DataHashes)).EncodingLength())
					l += uint(len(value.DataHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *AppendRequestParsingContext) Init() {

}

func (encoder *AppendRequestEncoder) EncodeInto(value *AppendRequest, buf []byte) {

	pos := uint(0)

	if value.DataHashes != nil {
		for seq_i, seq_v := range value.DataHashes {
			pseudoEncoder := &encoder.DataHashes_subencoder[seq_i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.DataHashes != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
					pos += 3
					pos += uint(enc.TLNum(len(value.DataHashes)).EncodeInto(buf[pos:]))
					copy(buf[pos:], value.DataHashes)
					pos += uint(len(value.DataHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *AppendRequestEncoder) Encode(value *AppendRequest) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *AppendRequestParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*AppendRequest, error) {

	var handled_DataHashes bool = false

	progress := -1
	_ = progress

	value := &AppendRequest{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7680:
				if true {
					handled = true
					handled_DataHashes = true
					if value.DataHashes == nil {
						value.DataHashes = make([][]byte, 0)
					}
					{
						pseudoValue := struct {
							DataHashes []byte
						}{}
						{
							value := &pseudoValue
							value.DataHashes = make([]byte, l)
							_, err = reader.ReadFull(value.DataHashes)
							_ = value
						}
						value.DataHashes = append(value.DataHashes, pseudoValue.DataHashes)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_DataHashes && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *AppendRequest) Encode() enc.Wire {
	encoder := AppendRequestEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *AppendRequest) Bytes() []byte {
	return value.Encode().Join()
}

func ParseAppendRequest(reader enc.WireView, ignoreCritical bool) (*AppendRequest, error) {
	context := AppendRequestParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type AppendResponseEncoder struct {
	Length uint

	Results_subencoder []struct {
		Results_encoder AppendResultEncoder
	}
}

type AppendResponseParsingContext struct {
	Results_context AppendResultParsingContext
}

func (encoder *AppendResponseEncoder) Init(value *AppendResponse) {
	{
		Results_l := len(value.Results)
		encoder.Results_subencoder = make([]struct {
			Results_encoder AppendResultEncoder
		}, Results_l)
		for i := 0; i < Results_l; i++ {
			pseudoEncoder := &encoder.Results_subencoder[i]
			pseudoValue := struct {
				Results *AppendResult
			}{
				Results: value.Results[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Results != nil {
					encoder.Results_encoder.Init(value.Results)
				}
				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.Results != nil {
		for seq_i, seq_v := range value.Results {
			pseudoEncoder := &encoder.Results_subencoder[seq_i]
			pseudoValue := struct {
				Results *AppendResult
			}{
				Results: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Results != nil {
					l += 3
					l += uint(enc.TLNum(encoder.Results_encoder.Length).EncodingLength())
					l += encoder.Results_encoder.Length
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *AppendResponseParsingContext) Init() {
	context.Results_context.Init()
}

func (encoder *AppendResponseEncoder) EncodeInto(value *AppendResponse, buf []byte) {

	pos := uint(0)

	if value.Results != nil {
		for seq_i, seq_v := range value.Results {
			pseudoEncoder := &encoder.Results_subencoder[seq_i]
			pseudoValue := struct {
				Results *AppendResult
			}{
				Results: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Results != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(7682))
					pos += 3
					pos += uint(enc.TLNum(encoder.Results_encoder.Length).EncodeInto(buf[pos:]))
					if encoder.Results_encoder.Length > 0 {
						encoder.Results_encoder.EncodeInto(value.Results, buf[pos:])
						pos += encoder.Results_encoder.Length
					}
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *AppendResponseEncoder) Encode(value *AppendResponse) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *AppendResponseParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*AppendResponse, error) {

	var handled_Results bool = false

	progress := -1
	_ = progress

	value := &AppendResponse{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7682:
				if true {
					handled = true
					handled_Results = true
					if value.Results == nil {
						value.Results = make([]*AppendResult, 0)
					}
					{
						pseudoValue := struct {
							Results *AppendResult
						}{}
						{
							value := &pseudoValue
							value.Results, err = context.Results_context.Parse(reader.Delegate(int(l)), ignoreCritical)
							_ = value
						}
						value.Results = append(value.Results, pseudoValue.Results)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Results && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *AppendResponse) Encode() enc.Wire {
	encoder := AppendResponseEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *AppendResponse) Bytes() []byte {
	return value.Encode().Join()
}

func ParseAppendResponse(reader enc.WireView, ignoreCritical bool) (*AppendResponse, error) {
	context := AppendResponseParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type AppendResultEncoder struct {
	Length uint
}

type AppendResultParsingContext struct {
}

func (encoder *AppendResultEncoder) Init(value *AppendResult) {

	l := uint(0)
	if value.DataHash != nil {
		l += 3
		l += uint(enc.TLNum(len(value.DataHash)).EncodingLength())
		l += uint(len(value.DataHash))
	}
	l += 3
	l += uint(1 + enc.Nat(value.Status).EncodingLength())
	if optval, ok := value.LeafIndex.Get(); ok {
		l += 3
		l += uint(1 + enc.Nat(optval).EncodingLength())
	}
	encoder.Length = l

}

func (context *AppendResultParsingContext) Init() {

}

func (encoder *AppendResultEncoder) EncodeInto(value *AppendResult, buf []byte) {

	pos := uint(0)

	if value.DataHash != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
		pos += 3
		pos += uint(enc.TLNum(len(value.DataHash)).EncodeInto(buf[pos:]))
		copy(buf[pos:], value.DataHash)
		pos += uint(len(value.DataHash))
	}
	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7684))
	pos += 3

	buf[pos] = byte(enc.Nat(value.Status).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	if optval, ok := value.LeafIndex.Get(); ok {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7686))
		pos += 3

		buf[pos] = byte(enc.Nat(optval).EncodeInto(buf[pos+1:]))
		pos += uint(1 + buf[pos])

	}
}

func (encoder *AppendResultEncoder) Encode(value *AppendResult) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *AppendResultParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*AppendResult, error) {

	var handled_DataHash bool = false
	var handled_Status bool = false
	var handled_LeafIndex bool = false

	progress := -1
	_ = progress

	value := &AppendResult{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7680:
				if true {
					handled = true
					handled_DataHash = true
					value.DataHash = make([]byte, l)
					_, err = reader.ReadFull(value.DataHash)
				}
			case 7684:
				if true {
					handled = true
					handled_Status = true
					value.Status = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.Status = uint64(value.Status<<8) | uint64(x)
						}
					}
				}
			case 7686:
				if true {
					handled = true
					handled_LeafIndex = true
					{
						optval := uint64(0)
						optval = uint64(0)
						{
							for i := 0; i < int(l); i++ {
								x := byte(0)
								x, err = reader.ReadByte()
								if err != nil {
									if err == io.EOF {
										err = io.ErrUnexpectedEOF
									}
									break
								}
								optval = uint64(optval<<8) | uint64(x)
							}
						}
						value.LeafIndex.Set(optval)
					}
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_DataHash && err == nil {
		value.DataHash = nil
	}
	if !handled_Status && err == nil {
		err = enc.ErrSkipRequired{Name: "Status", TypeNum: 7684}
	}
	if !handled_LeafIndex && err == nil {
		value.LeafIndex.Unset()
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *AppendResult) Encode() enc.Wire {
	encoder := AppendResultEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *AppendResult) Bytes() []byte {
	return value.Encode().Join()
}

func ParseAppendResult(reader enc.WireView, ignoreCritical bool) (*AppendResult, error) {
	context := AppendResultParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type CheckRequestEncoder struct {
	Length uint

	DataHashes_subencoder []struct {
	}
}

type CheckRequestParsingContext struct {
}

func (encoder *CheckRequestEncoder) Init(value *CheckRequest) {
	{
		DataHashes_l := len(value.DataHashes)
		encoder.DataHashes_subencoder = make([]struct {
		}, DataHashes_l)
		for i := 0; i < DataHashes_l; i++ {
			pseudoEncoder := &encoder.DataHashes_subencoder[i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: value.DataHashes[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue

				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.DataHashes != nil {
		for seq_i, seq_v := range value.DataHashes {
			pseudoEncoder := &encoder.DataHashes_subencoder[seq_i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.DataHashes != nil {
					l += 3
					l += uint(enc.TLNum(len(value.DataHashes)).EncodingLength())
					l += uint(len(value.DataHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *CheckRequestParsingContext) Init() {

}

func (encoder *CheckRequestEncoder) EncodeInto(value *CheckRequest, buf []byte) {

	pos := uint(0)

	if value.DataHashes != nil {
		for seq_i, seq_v := range value.DataHashes {
			pseudoEncoder := &encoder.DataHashes_subencoder[seq_i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.DataHashes != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
					pos += 3
					pos += uint(enc.TLNum(len(value.DataHashes)).EncodeInto(buf[pos:]))
					copy(buf[pos:], value.DataHashes)
					pos += uint(len(value.DataHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *CheckRequestEncoder) Encode(value *CheckRequest) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *CheckRequestParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*CheckRequest, error) {

	var handled_DataHashes bool = false

	progress := -1
	_ = progress

	value := &CheckRequest{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7680:
				if true {
					handled = true
					handled_DataHashes = true
					if value.DataHashes == nil {
						value.DataHashes = make([][]byte, 0)
					}
					{
						pseudoValue := struct {
							DataHashes []byte
						}{}
						{
							value := &pseudoValue
							value.DataHashes = make([]byte, l)
							_, err = reader.ReadFull(value.DataHashes)
							_ = value
						}
						value.DataHashes = append(value.DataHashes, pseudoValue.DataHashes)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_DataHashes && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *CheckRequest) Encode() enc.Wire {
	encoder := CheckRequestEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *CheckRequest) Bytes() []byte {
	return value.Encode().Join()
}

func ParseCheckRequest(reader enc.WireView, ignoreCritical bool) (*CheckRequest, error) {
	context := CheckRequestParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type CheckResponseEncoder struct {
	Length uint

	Root_encoder       TreeRootEncoder
	Results_subencoder []struct {
		Results_encoder CheckResultEncoder
	}
}

type CheckResponseParsingContext struct {
	Root_context    TreeRootParsingContext
	Results_context CheckResultParsingContext
}

func (encoder *CheckResponseEncoder) Init(value *CheckResponse) {
	if value.Root != nil {
		encoder.Root_encoder.Init(value.Root)
	}
	{
		Results_l := len(value.Results)
		encoder.Results_subencoder = make([]struct {
			Results_encoder CheckResultEncoder
		}, Results_l)
		for i := 0; i < Results_l; i++ {
			pseudoEncoder := &encoder.Results_subencoder[i]
			pseudoValue := struct {
				Results *CheckResult
			}{
				Results: value.Results[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Results != nil {
					encoder.Results_encoder.Init(value.Results)
				}
				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.Root != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Root_encoder.Length).EncodingLength())
		l += encoder.Root_encoder.Length
	}
	if value.Results != nil {
		for seq_i, seq_v := range value.Results {
			pseudoEncoder := &encoder.Results_subencoder[seq_i]
			pseudoValue := struct {
				Results *CheckResult
			}{
				Results: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Results != nil {
					l += 3
					l += uint(enc.TLNum(encoder.Results_encoder.Length).EncodingLength())
					l += encoder.Results_encoder.Length
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *CheckResponseParsingContext) Init() {
	context.Root_context.Init()
	context.Results_context.Init()
}

func (encoder *CheckResponseEncoder) EncodeInto(value *CheckResponse, buf []byte) {

	pos := uint(0)

	if value.Root != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7688))
		pos += 3
		pos += uint(enc.TLNum(encoder.Root_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Root_encoder.Length > 0 {
			encoder.Root_encoder.EncodeInto(value.Root, buf[pos:])
			pos += encoder.Root_encoder.Length
		}
	}
	if value.Results != nil {
		for seq_i, seq_v := range value.Results {
			pseudoEncoder := &encoder.Results_subencoder[seq_i]
			pseudoValue := struct {
				Results *CheckResult
			}{
				Results: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Results != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(7690))
					pos += 3
					pos += uint(enc.TLNum(encoder.Results_encoder.Length).EncodeInto(buf[pos:]))
					if encoder.Results_encoder.Length > 0 {
						encoder.Results_encoder.EncodeInto(value.Results, buf[pos:])
						pos += encoder.Results_encoder.Length
					}
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *CheckResponseEncoder) Encode(value *CheckResponse) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *CheckResponseParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*CheckResponse, error) {

	var handled_Root bool = false
	var handled_Results bool = false

	progress := -1
	_ = progress

	value := &CheckResponse{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7688:
				if true {
					handled = true
					handled_Root = true
					value.Root, err = context.Root_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7690:
				if true {
					handled = true
					handled_Results = true
					if value.Results == nil {
						value.Results = make([]*CheckResult, 0)
					}
					{
						pseudoValue := struct {
							Results *CheckResult
						}{}
						{
							value := &pseudoValue
							value.Results, err = context.Results_context.Parse(reader.Delegate(int(l)), ignoreCritical)
							_ = value
						}
						value.Results = append(value.Results, pseudoValue.Results)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Root && err == nil {
		value.Root = nil
	}
	if !handled_Results && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *CheckResponse) Encode() enc.Wire {
	encoder := CheckResponseEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *CheckResponse) Bytes() []byte {
	return value.Encode().Join()
}

func ParseCheckResponse(reader enc.WireView, ignoreCritical bool) (*CheckResponse, error) {
	context := CheckResponseParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type CheckResultEncoder struct {
	Length uint

	Proof_encoder InclusionProofEncoder
}

type CheckResultParsingContext struct {
	Proof_context InclusionProofParsingContext
}

func (encoder *CheckResultEncoder) Init(value *CheckResult) {

	if value.Proof != nil {
		encoder.Proof_encoder.Init(value.Proof)
	}

	l := uint(0)
	if value.DataHash != nil {
		l += 3
		l += uint(enc.TLNum(len(value.DataHash)).EncodingLength())
		l += uint(len(value.DataHash))
	}
	l += 3
	l += uint(1 + enc.Nat(value.Status).EncodingLength())
	if value.Proof != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Proof_encoder.Length).EncodingLength())
		l += encoder.Proof_encoder.Length
	}
	encoder.Length = l

}

func (context *CheckResultParsingContext) Init() {

	context.Proof_context.Init()
}

func (encoder *CheckResultEncoder) EncodeInto(value *CheckResult, buf []byte) {

	pos := uint(0)

	if value.DataHash != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
		pos += 3
		pos += uint(enc.TLNum(len(value.DataHash)).EncodeInto(buf[pos:]))
		copy(buf[pos:], value.DataHash)
		pos += uint(len(value.DataHash))
	}
	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7684))
	pos += 3

	buf[pos] = byte(enc.Nat(value.Status).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	if value.Proof != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7692))
		pos += 3
		pos += uint(enc.TLNum(encoder.Proof_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Proof_encoder.Length > 0 {
			encoder.Proof_encoder.EncodeInto(value.Proof, buf[pos:])
			pos += encoder.Proof_encoder.Length
		}
	}
}

func (encoder *CheckResultEncoder) Encode(value *CheckResult) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *CheckResultParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*CheckResult, error) {

	var handled_DataHash bool = false
	var handled_Status bool = false
	var handled_Proof bool = false

	progress := -1
	_ = progress

	value := &CheckResult{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7680:
				if true {
					handled = true
					handled_DataHash = true
					value.DataHash = make([]byte, l)
					_, err = reader.ReadFull(value.DataHash)
				}
			case 7684:
				if true {
					handled = true
					handled_Status = true
					value.Status = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.Status = uint64(value.Status<<8) | uint64(x)
						}
					}
				}
			case 7692:
				if true {
					handled = true
					handled_Proof = true
					value.Proof, err = context.Proof_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_DataHash && err == nil {
		value.DataHash = nil
	}
	if !handled_Status && err == nil {
		err = enc.ErrSkipRequired{Name: "Status", TypeNum: 7684}
	}
	if !handled_Proof && err == nil {
		value.Proof = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *CheckResult) Encode() enc.Wire {
	encoder := CheckResultEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *CheckResult) Bytes() []byte {
	return value.Encode().Join()
}

func ParseCheckResult(reader enc.WireView, ignoreCritical bool) (*CheckResult, error) {
	context := CheckResultParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type TreeRootEncoder struct {
	Length uint
}

type TreeRootParsingContext struct {
}

func (encoder *TreeRootEncoder) Init(value *TreeRoot) {

	l := uint(0)
	l += 3
	l += uint(1 + enc.Nat(value.TreeSize).EncodingLength())
	if value.RootHash != nil {
		l += 3
		l += uint(enc.TLNum(len(value.RootHash)).EncodingLength())
		l += uint(len(value.RootHash))
	}
	encoder.Length = l

}

func (context *TreeRootParsingContext) Init() {

}

func (encoder *TreeRootEncoder) EncodeInto(value *TreeRoot, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7694))
	pos += 3

	buf[pos] = byte(enc.Nat(value.TreeSize).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	if value.RootHash != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7696))
		pos += 3
		pos += uint(enc.TLNum(len(value.RootHash)).EncodeInto(buf[pos:]))
		copy(buf[pos:], value.RootHash)
		pos += uint(len(value.RootHash))
	}
}

func (encoder *TreeRootEncoder) Encode(value *TreeRoot) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *TreeRootParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*TreeRoot, error) {

	var handled_TreeSize bool = false
	var handled_RootHash bool = false

	progress := -1
	_ = progress

	value := &TreeRoot{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7694:
				if true {
					handled = true
					handled_TreeSize = true
					value.TreeSize = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.TreeSize = uint64(value.TreeSize<<8) | uint64(x)
						}
					}
				}
			case 7696:
				if true {
					handled = true
					handled_RootHash = true
					value.RootHash = make([]byte, l)
					_, err = reader.ReadFull(value.RootHash)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_TreeSize && err == nil {
		err = enc.ErrSkipRequired{Name: "TreeSize", TypeNum: 7694}
	}
	if !handled_RootHash && err == nil {
		value.RootHash = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *TreeRoot) Encode() enc.Wire {
	encoder := TreeRootEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *TreeRoot) Bytes() []byte {
	return value.Encode().Join()
}

func ParseTreeRoot(reader enc.WireView, ignoreCritical bool) (*TreeRoot, error) {
	context := TreeRootParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type InclusionProofEncoder struct {
	Length uint

	Entry_length uint

	SiblingHashes_subencoder []struct {
	}
}

type InclusionProofParsingContext struct {
}

func (encoder *InclusionProofEncoder) Init(value *InclusionProof) {
	if value.Entry != nil {
		encoder.Entry_length = 0
		for _, c := range value.Entry {
			encoder.Entry_length += uint(len(c))
		}
	}

	{
		SiblingHashes_l := len(value.SiblingHashes)
		encoder.SiblingHashes_subencoder = make([]struct {
		}, SiblingHashes_l)
		for i := 0; i < SiblingHashes_l; i++ {
			pseudoEncoder := &encoder.SiblingHashes_subencoder[i]
			pseudoValue := struct {
				SiblingHashes []byte
			}{
				SiblingHashes: value.SiblingHashes[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue

				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.Entry != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Entry_length).EncodingLength())
		l += encoder.Entry_length
	}
	l += 3
	l += uint(1 + enc.Nat(value.LeafIndex).EncodingLength())
	if value.SiblingHashes != nil {
		for seq_i, seq_v := range value.SiblingHashes {
			pseudoEncoder := &encoder.SiblingHashes_subencoder[seq_i]
			pseudoValue := struct {
				SiblingHashes []byte
			}{
				SiblingHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.SiblingHashes != nil {
					l += 3
					l += uint(enc.TLNum(len(value.SiblingHashes)).EncodingLength())
					l += uint(len(value.SiblingHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *InclusionProofParsingContext) Init() {

}

func (encoder *InclusionProofEncoder) EncodeInto(value *InclusionProof, buf []byte) {

	pos := uint(0)

	if value.Entry != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7698))
		pos += 3
		pos += uint(enc.TLNum(encoder.Entry_length).EncodeInto(buf[pos:]))
		for _, w := range value.Entry {
			copy(buf[pos:], w)
			pos += uint(len(w))
		}
	}
	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7686))
	pos += 3

	buf[pos] = byte(enc.Nat(value.LeafIndex).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	if value.SiblingHashes != nil {
		for seq_i, seq_v := range value.SiblingHashes {
			pseudoEncoder := &encoder.SiblingHashes_subencoder[seq_i]
			pseudoValue := struct {
				SiblingHashes []byte
			}{
				SiblingHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.SiblingHashes != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(7700))
					pos += 3
					pos += uint(enc.TLNum(len(value.SiblingHashes)).EncodeInto(buf[pos:]))
					copy(buf[pos:], value.SiblingHashes)
					pos += uint(len(value.SiblingHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *InclusionProofEncoder) Encode(value *InclusionProof) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *InclusionProofParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*InclusionProof, error) {

	var handled_Entry bool = false
	var handled_LeafIndex bool = false
	var handled_SiblingHashes bool = false

	progress := -1
	_ = progress

	value := &InclusionProof{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7698:
				if true {
					handled = true
					handled_Entry = true
					value.Entry, err = reader.ReadWire(int(l))
				}
			case 7686:
				if true {
					handled = true
					handled_LeafIndex = true
					value.LeafIndex = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.LeafIndex = uint64(value.LeafIndex<<8) | uint64(x)
						}
					}
				}
			case 7700:
				if true {
					handled = true
					handled_SiblingHashes = true
					if value.SiblingHashes == nil {
						value.SiblingHashes = make([][]byte, 0)
					}
					{
						pseudoValue := struct {
							SiblingHashes []byte
						}{}
						{
							value := &pseudoValue
							value.SiblingHashes = make([]byte, l)
							_, err = reader.ReadFull(value.SiblingHashes)
							_ = value
						}
						value.SiblingHashes = append(value.SiblingHashes, pseudoValue.SiblingHashes)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Entry && err == nil {
		value.Entry = nil
	}
	if !handled_LeafIndex && err == nil {
		err = enc.ErrSkipRequired{Name: "LeafIndex", TypeNum: 7686}
	}
	if !handled_SiblingHashes && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *InclusionProof) Encode() enc.Wire {
	encoder := InclusionProofEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *InclusionProof) Bytes() []byte {
	return value.Encode().Join()
}

func ParseInclusionProof(reader enc.WireView, ignoreCritical bool) (*InclusionProof, error) {
	context := InclusionProofParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type LogEntryEncoder struct {
	Length uint

	DataHashes_subencoder []struct {
	}
}

type LogEntryParsingContext struct {
}

func (encoder *LogEntryEncoder) Init(value *LogEntry) {

	{
		DataHashes_l := len(value.DataHashes)
		encoder.DataHashes_subencoder = make([]struct {
		}, DataHashes_l)
		for i := 0; i < DataHashes_l; i++ {
			pseudoEncoder := &encoder.DataHashes_subencoder[i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: value.DataHashes[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue

				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	l += 3
	l += uint(1 + enc.Nat(uint64(value.IngestTime/time.Millisecond)).EncodingLength())
	if value.DataHashes != nil {
		for seq_i, seq_v := range value.DataHashes {
			pseudoEncoder := &encoder.DataHashes_subencoder[seq_i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.DataHashes != nil {
					l += 3
					l += uint(enc.TLNum(len(value.DataHashes)).EncodingLength())
					l += uint(len(value.DataHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *LogEntryParsingContext) Init() {

}

func (encoder *LogEntryEncoder) EncodeInto(value *LogEntry, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7702))
	pos += 3

	buf[pos] = byte(enc.Nat(uint64(value.IngestTime / time.Millisecond)).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	if value.DataHashes != nil {
		for seq_i, seq_v := range value.DataHashes {
			pseudoEncoder := &encoder.DataHashes_subencoder[seq_i]
			pseudoValue := struct {
				DataHashes []byte
			}{
				DataHashes: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.DataHashes != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
					pos += 3
					pos += uint(enc.TLNum(len(value.DataHashes)).EncodeInto(buf[pos:]))
					copy(buf[pos:], value.DataHashes)
					pos += uint(len(value.DataHashes))
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *LogEntryEncoder) Encode(value *LogEntry) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *LogEntryParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*LogEntry, error) {

	var handled_IngestTime bool = false
	var handled_DataHashes bool = false

	progress := -1
	_ = progress

	value := &LogEntry{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7702:
				if true {
					handled = true
					handled_IngestTime = true
					{
						timeInt := uint64(0)
						timeInt = uint64(0)
						{
							for i := 0; i < int(l); i++ {
								x := byte(0)
								x, err = reader.ReadByte()
								if err != nil {
									if err == io.EOF {
										err = io.ErrUnexpectedEOF
									}
									break
								}
								timeInt = uint64(timeInt<<8) | uint64(x)
							}
						}
						value.IngestTime = time.Duration(timeInt) * time.Millisecond
					}
				}
			case 7680:
				if true {
					handled = true
					handled_DataHashes = true
					if value.DataHashes == nil {
						value.DataHashes = make([][]byte, 0)
					}
					{
						pseudoValue := struct {
							DataHashes []byte
						}{}
						{
							value := &pseudoValue
							value.DataHashes = make([]byte, l)
							_, err = reader.ReadFull(value.DataHashes)
							_ = value
						}
						value.DataHashes = append(value.DataHashes, pseudoValue.DataHashes)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_IngestTime && err == nil {
		err = enc.ErrSkipRequired{Name: "IngestTime", TypeNum: 7702}
	}
	if !handled_DataHashes && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *LogEntry) Encode() enc.Wire {
	encoder := LogEntryEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *LogEntry) Bytes() []byte {
	return value.Encode().Join()
}

func ParseLogEntry(reader enc.WireView, ignoreCritical bool) (*LogEntry, error) {
	context := LogEntryParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}
