// Code generated by ndn tlv codegen DO NOT EDIT.
package revocationtlv

import (
	"io"

	enc "github.com/named-data/ndnd/std/encoding"
)

type RevocationRecordEncoder struct {
	Length uint
}

type RevocationRecordParsingContext struct {
}

func (encoder *RevocationRecordEncoder) Init(value *RevocationRecord) {

	l := uint(0)
	l += 1
	l += uint(1 + enc.Nat(value.Timestamp).EncodingLength())
	l += 1
	l += uint(1 + enc.Nat(value.Reason).EncodingLength())
	if value.PublicKeyHash != nil {
		l += 1
		l += uint(enc.TLNum(len(value.PublicKeyHash)).EncodingLength())
		l += uint(len(value.PublicKeyHash))
	}
	if optval, ok := value.NotBefore.Get(); ok {
		l += 1
		l += uint(1 + enc.Nat(optval).EncodingLength())
	}
	encoder.Length = l

}

func (context *RevocationRecordParsingContext) Init() {

}

func (encoder *RevocationRecordEncoder) EncodeInto(value *RevocationRecord, buf []byte) {

	pos := uint(0)

	buf[pos] = byte(201)
	pos += 1

	buf[pos] = byte(enc.Nat(value.Timestamp).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	buf[pos] = byte(203)
	pos += 1

	buf[pos] = byte(enc.Nat(value.Reason).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	if value.PublicKeyHash != nil {
		buf[pos] = byte(202)
		pos += 1
		pos += uint(enc.TLNum(len(value.PublicKeyHash)).EncodeInto(buf[pos:]))
		copy(buf[pos:], value.PublicKeyHash)
		pos += uint(len(value.PublicKeyHash))
	}
	if optval, ok := value.NotBefore.Get(); ok {
		buf[pos] = byte(205)
		pos += 1

		buf[pos] = byte(enc.Nat(optval).EncodeInto(buf[pos+1:]))
		pos += uint(1 + buf[pos])

	}
}

func (encoder *RevocationRecordEncoder) Encode(value *RevocationRecord) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *RevocationRecordParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*RevocationRecord, error) {

	var handled_Timestamp bool = false
	var handled_Reason bool = false
	var handled_PublicKeyHash bool = false
	var handled_NotBefore bool = false

	progress := -1
	_ = progress

	value := &RevocationRecord{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		for handled := false; !handled && progress < 4; progress++ {
			switch typ {
			case 201:
				if progress+1 == 0 {
					handled = true
					handled_Timestamp = true
					value.Timestamp = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.Timestamp = uint64(value.Timestamp<<8) | uint64(x)
						}
					}
				}
			case 203:
				if progress+1 == 1 {
					handled = true
					handled_Reason = true
					value.Reason = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.Reason = uint64(value.Reason<<8) | uint64(x)
						}
					}
				}
			case 202:
				if progress+1 == 2 {
					handled = true
					handled_PublicKeyHash = true
					value.PublicKeyHash = make([]byte, l)
					_, err = reader.ReadFull(value.PublicKeyHash)
				}
			case 205:
				if progress+1 == 3 {
					handled = true
					handled_NotBefore = true
					{
						optval := uint64(0)
						optval = uint64(0)
						{
							for i := 0; i < int(l); i++ {
								x := byte(0)
								x, err = reader.ReadByte()
								if err != nil {
									if err == io.EOF {
										err = io.ErrUnexpectedEOF
									}
									break
								}
								optval = uint64(optval<<8) | uint64(x)
							}
						}
						value.NotBefore.Set(optval)
					}
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
				switch progress {
				case 0 - 1:
					handled_Timestamp = true
					err = enc.ErrSkipRequired{Name: "Timestamp", TypeNum: 201}
				case 1 - 1:
					handled_Reason = true
					err = enc.ErrSkipRequired{Name: "Reason", TypeNum: 203}
				case 2 - 1:
					handled_PublicKeyHash = true
					value.PublicKeyHash = nil
				case 3 - 1:
					handled_NotBefore = true
					value.NotBefore.Unset()
				}
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Timestamp && err == nil {
		err = enc.ErrSkipRequired{Name: "Timestamp", TypeNum: 201}
	}
	if !handled_Reason && err == nil {
		err = enc.ErrSkipRequired{Name: "Reason", TypeNum: 203}
	}
	if !handled_PublicKeyHash && err == nil {
		value.PublicKeyHash = nil
	}
	if !handled_NotBefore && err == nil {
		value.NotBefore.Unset()
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *RevocationRecord) Encode() enc.Wire {
	encoder := RevocationRecordEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *RevocationRecord) Bytes() []byte {
	return value.Encode().Join()
}

func ParseRevocationRecord(reader enc.WireView, ignoreCritical bool) (*RevocationRecord, error) {
	context := RevocationRecordParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}
